/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import javax.swing.JOptionPane;

/**
 *
 * @author FAWZAN
 */
public class AddNewCustomer extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public AddNewCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emailField2 = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        securityQuesField = new javax.swing.JTextField();
        securityAnsField = new javax.swing.JTextField();
        passwordField2 = new javax.swing.JPasswordField();
        passwordField3 = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        labelWelcome1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 150));
        jPanel1.setMaximumSize(new java.awt.Dimension(340, 460));
        jPanel1.setMinimumSize(new java.awt.Dimension(340, 460));
        jPanel1.setPreferredSize(new java.awt.Dimension(340, 460));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 110, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 110, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Phone");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 110, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Security Question");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 170, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Security Answer");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 170, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Password");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 110, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Confirm Password");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 170, 30));

        emailField2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        emailField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailField2ActionPerformed(evt);
            }
        });
        emailField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailField2KeyPressed(evt);
            }
        });
        jPanel1.add(emailField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 200, 30));

        nameField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameFieldKeyPressed(evt);
            }
        });
        jPanel1.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 200, 30));

        phoneField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });
        phoneField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneFieldKeyPressed(evt);
            }
        });
        jPanel1.add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 200, 30));

        securityQuesField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        securityQuesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityQuesFieldActionPerformed(evt);
            }
        });
        securityQuesField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                securityQuesFieldKeyPressed(evt);
            }
        });
        jPanel1.add(securityQuesField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 200, 30));

        securityAnsField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        securityAnsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityAnsFieldActionPerformed(evt);
            }
        });
        securityAnsField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                securityAnsFieldKeyPressed(evt);
            }
        });
        jPanel1.add(securityAnsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 200, 30));

        passwordField2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        passwordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordField2KeyPressed(evt);
            }
        });
        jPanel1.add(passwordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 200, 30));

        passwordField3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        passwordField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordField3KeyPressed(evt);
            }
        });
        jPanel1.add(passwordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 200, 30));

        registerButton.setBackground(new java.awt.Color(153, 153, 255));
        registerButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 140, 45));

        labelWelcome1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelWelcome1.setForeground(new java.awt.Color(255, 255, 255));
        labelWelcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWelcome1.setText("Add New User");
        jPanel1.add(labelWelcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 380, -1));

        backButton.setBackground(new java.awt.Color(153, 153, 255));
        backButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 140, 45));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 540, 540));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/images/pexels-engin-akyurt-1435904.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordField2KeyPressed
        
    }//GEN-LAST:event_passwordField2KeyPressed

    private void securityAnsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityAnsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityAnsFieldActionPerformed

    private void securityAnsFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_securityAnsFieldKeyPressed
        
    }//GEN-LAST:event_securityAnsFieldKeyPressed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String email = emailField2.getText().toLowerCase();
        String name = nameField.getText();
        String phone = phoneField.getText();
        String securityQ = securityQuesField.getText();
        String securityAns = securityAnsField.getText();
        String password = String.valueOf(passwordField2.getPassword());
        String confirmPass = String.valueOf(passwordField3.getPassword());
        
        
        Customer customer = new Customer(name, email, phone, password, confirmPass, securityQ, securityAns);
        
        if(customer.validate())
        {
            if(customer.register() != null)
            {
                this.setVisible(false);
                CustomerManagement cmf = new CustomerManagement();
                cmf.setLocation(this.getLocation());
                cmf.setVisible(true);
                cmf.setResizable(false);
            }
            
            
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void passwordField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordField3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordField3KeyPressed

    private void emailField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailField2ActionPerformed

    private void emailField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailField2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailField2KeyPressed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void nameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldKeyPressed

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldActionPerformed

    private void phoneFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldKeyPressed

    private void securityQuesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityQuesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityQuesFieldActionPerformed

    private void securityQuesFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_securityQuesFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityQuesFieldKeyPressed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        CustomerManagement cmf = new CustomerManagement();
        cmf.setLocation(this.getLocation());
        cmf.setVisible(true);
        cmf.setResizable(false);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField emailField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelWelcome1;
    private javax.swing.JTextField nameField;
    private javax.swing.JPasswordField passwordField2;
    private javax.swing.JPasswordField passwordField3;
    private javax.swing.JTextField phoneField;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField securityAnsField;
    private javax.swing.JTextField securityQuesField;
    // End of variables declaration//GEN-END:variables
}
