/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FAWZAN
 */
public class AddPayment extends javax.swing.JFrame {

    private Booking booking;
    private Car car;
    private float total;
    /**
     * Creates new form AdminDashboard
     * @param booking
     */
    public AddPayment(Booking booking) {
        initComponents();
        
        this.booking = booking;
        this.car = new Car(booking.carId);
        long differenceInTime = this.booking.checkinDate.getTime() - this.booking.checkoutDate.getTime();
        long differenceInDay = (differenceInTime / (1000 * 60 * 60 * 24));
        this.total = Integer.valueOf(this.car.rent) * (differenceInDay + 1);
        System.out.println(this.total);
        totalField.setText(String.valueOf(this.total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        manufacturerLabel = new javax.swing.JLabel();
        cardNumberField = new javax.swing.JTextField();
        modelLabel = new javax.swing.JLabel();
        cardHolderField = new javax.swing.JTextField();
        colorLabel = new javax.swing.JLabel();
        expiryDateField = new javax.swing.JTextField();
        seatsLabel = new javax.swing.JLabel();
        cvvField = new javax.swing.JTextField();
        rentLabel = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 150));
        jPanel1.setMaximumSize(new java.awt.Dimension(340, 460));
        jPanel1.setMinimumSize(new java.awt.Dimension(340, 460));
        jPanel1.setPreferredSize(new java.awt.Dimension(340, 460));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pay");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 380, -1));

        saveButton.setBackground(new java.awt.Color(153, 153, 255));
        saveButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 160, 45));

        cancelButton.setBackground(new java.awt.Color(153, 153, 255));
        cancelButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 140, 45));

        manufacturerLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        manufacturerLabel.setForeground(new java.awt.Color(255, 255, 255));
        manufacturerLabel.setText("Card Number");
        jPanel1.add(manufacturerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 160, 30));

        cardNumberField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        cardNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberFieldActionPerformed(evt);
            }
        });
        cardNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cardNumberFieldKeyPressed(evt);
            }
        });
        jPanel1.add(cardNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 200, 30));

        modelLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        modelLabel.setForeground(new java.awt.Color(255, 255, 255));
        modelLabel.setText("Card Holder");
        jPanel1.add(modelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 110, 30));

        cardHolderField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        cardHolderField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardHolderFieldActionPerformed(evt);
            }
        });
        cardHolderField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cardHolderFieldKeyPressed(evt);
            }
        });
        jPanel1.add(cardHolderField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 200, 30));

        colorLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        colorLabel.setForeground(new java.awt.Color(255, 255, 255));
        colorLabel.setText("Expiry Date");
        jPanel1.add(colorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 120, 30));

        expiryDateField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        expiryDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiryDateFieldActionPerformed(evt);
            }
        });
        expiryDateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                expiryDateFieldKeyPressed(evt);
            }
        });
        jPanel1.add(expiryDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 200, 30));

        seatsLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        seatsLabel.setForeground(new java.awt.Color(255, 255, 255));
        seatsLabel.setText("CVV");
        jPanel1.add(seatsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 110, 30));

        cvvField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        cvvField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvFieldActionPerformed(evt);
            }
        });
        cvvField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cvvFieldKeyPressed(evt);
            }
        });
        jPanel1.add(cvvField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 200, 30));

        rentLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rentLabel.setForeground(new java.awt.Color(255, 255, 255));
        rentLabel.setText("Total in RM");
        jPanel1.add(rentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 160, 30));

        totalField.setEditable(false);
        totalField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        totalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFieldActionPerformed(evt);
            }
        });
        totalField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totalFieldKeyPressed(evt);
            }
        });
        jPanel1.add(totalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 200, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 490, 470));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/images/pexels-engin-akyurt-1435904.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String cardNumber = cardNumberField.getText();
        String cardHolder = cardHolderField.getText();
        String expiryDate = expiryDateField.getText();
        String cvv = cvvField.getText();
        
        
        
        Payment payment = new Payment(booking.id, cardNumber, cardHolder, expiryDate, cvv, this.total);
        
        if(payment.validate())
        {
            if(payment.add() != null)
            {
                try {
                    this.booking.status = "Paid";
                    this.booking.update();
                    
                    this.setVisible(false);
                    BookingManagement bmf = new BookingManagement();
                    bmf.setLocation(this.getLocation());
                    bmf.setVisible(true);
                    bmf.setResizable(false);
                } catch (ParseException ex) {
                    Logger.getLogger(AddPayment.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        }
        
       
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        try {
            this.booking.status = "Cancelled";
            this.booking.update();

            this.setVisible(false);
            BookingManagement bmf = new BookingManagement();
            bmf.setLocation(this.getLocation());
            bmf.setVisible(true);
            bmf.setResizable(false);
        } catch (ParseException ex) {
            Logger.getLogger(AddPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void cardNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumberFieldActionPerformed

    private void cardNumberFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNumberFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumberFieldKeyPressed

    private void cardHolderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardHolderFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardHolderFieldActionPerformed

    private void cardHolderFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardHolderFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardHolderFieldKeyPressed

    private void expiryDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiryDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryDateFieldActionPerformed

    private void expiryDateFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expiryDateFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryDateFieldKeyPressed

    private void cvvFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvFieldActionPerformed

    private void cvvFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvvFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvFieldKeyPressed

    private void totalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFieldActionPerformed

    private void totalFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField cardHolderField;
    private javax.swing.JTextField cardNumberField;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JTextField cvvField;
    private javax.swing.JTextField expiryDateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel manufacturerLabel;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JLabel rentLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel seatsLabel;
    private javax.swing.JTextField totalField;
    // End of variables declaration//GEN-END:variables
}
