/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author FAWZAN
 */
public class AdminDashboard extends javax.swing.JFrame {


    
    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        paymentsButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        customersButton = new javax.swing.JButton();
        carsButton = new javax.swing.JButton();
        changeSecurityQuesButton = new javax.swing.JButton();
        bookingsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 150));
        jPanel1.setMaximumSize(new java.awt.Dimension(340, 460));
        jPanel1.setMinimumSize(new java.awt.Dimension(340, 460));
        jPanel1.setPreferredSize(new java.awt.Dimension(340, 460));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Admin Dashboard");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 31, 380, -1));

        paymentsButton.setBackground(new java.awt.Color(153, 153, 255));
        paymentsButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        paymentsButton.setForeground(new java.awt.Color(255, 255, 255));
        paymentsButton.setText("Payments");
        paymentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(paymentsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 140, 45));

        logoutButton.setBackground(new java.awt.Color(153, 153, 255));
        logoutButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 140, 45));

        customersButton.setBackground(new java.awt.Color(153, 153, 255));
        customersButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        customersButton.setForeground(new java.awt.Color(255, 255, 255));
        customersButton.setText("Customers");
        customersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersButtonActionPerformed(evt);
            }
        });
        jPanel1.add(customersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 140, 45));

        carsButton.setBackground(new java.awt.Color(153, 153, 255));
        carsButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        carsButton.setForeground(new java.awt.Color(255, 255, 255));
        carsButton.setText("Cars");
        carsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(carsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 140, 45));

        changeSecurityQuesButton.setBackground(new java.awt.Color(153, 153, 255));
        changeSecurityQuesButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        changeSecurityQuesButton.setForeground(new java.awt.Color(255, 255, 255));
        changeSecurityQuesButton.setText("Edit Personal Details");
        changeSecurityQuesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSecurityQuesButtonActionPerformed(evt);
            }
        });
        jPanel1.add(changeSecurityQuesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 310, 45));

        bookingsButton.setBackground(new java.awt.Color(153, 153, 255));
        bookingsButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bookingsButton.setForeground(new java.awt.Color(255, 255, 255));
        bookingsButton.setText("Bookings");
        bookingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(bookingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 140, 45));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 380, 430));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/images/pexels-engin-akyurt-1435904.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paymentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsButtonActionPerformed
        this.setVisible(false);
        PaymentManagement pmf = new PaymentManagement();
        pmf.setLocation(this.getLocation());
        pmf.setVisible(true);
        pmf.setResizable(false);

    }//GEN-LAST:event_paymentsButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.setVisible(false);
        Welcome wf = new Welcome();
        wf.setLocation(this.getLocation());
        wf.setVisible(true);
        wf.setResizable(false);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void customersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersButtonActionPerformed
        this.setVisible(false);
        CustomerManagement umf = new CustomerManagement();
        umf.setLocation(this.getLocation());
        umf.setVisible(true);
        umf.setResizable(false);
    }//GEN-LAST:event_customersButtonActionPerformed

    private void carsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carsButtonActionPerformed
        this.setVisible(false);
        CarManagement cmf = new CarManagement();
        cmf.setLocation(this.getLocation());
        cmf.setVisible(true);
        cmf.setResizable(false);
    }//GEN-LAST:event_carsButtonActionPerformed

    private void changeSecurityQuesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSecurityQuesButtonActionPerformed
        this.setVisible(false);
        EditAdmin eaf = new EditAdmin();
        eaf.setLocation(this.getLocation());
        eaf.setVisible(true);
        eaf.setResizable(false);
    }//GEN-LAST:event_changeSecurityQuesButtonActionPerformed

    private void bookingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingsButtonActionPerformed
        try {
            this.setVisible(false);
            BookingManagement bmf = new BookingManagement();
            bmf.setLocation(this.getLocation());
            bmf.setVisible(true);
            bmf.setResizable(false);
        } catch (ParseException ex) {
            Logger.getLogger(AdminDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bookingsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookingsButton;
    private javax.swing.JButton carsButton;
    private javax.swing.JButton changeSecurityQuesButton;
    private javax.swing.JButton customersButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton paymentsButton;
    // End of variables declaration//GEN-END:variables
}
