/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author FAWZAN
 */
public class CustomerManagement extends javax.swing.JFrame {

    private DefaultTableModel customerTable;
    //private Car[] cars = new Car[4];
    List<Customer> customers = new ArrayList<Customer>();
    /**
     * Creates new form AdminDashboard
     */
    public CustomerManagement() {
        initComponents();
        
        this.customerTable = (DefaultTableModel) jTable1.getModel();
        
        this.getAllCustomers();
        this.showAllCustomers();
    }

    private void getAllCustomers()
    {
        this.customerTable = (DefaultTableModel) jTable1.getModel();
        try  
        {  
            File customerFile = new File("files/customers.txt");
            if (customerFile.exists())
            {
                BufferedReader data;
                data = new BufferedReader(new FileReader(customerFile));
                String line;
                data.readLine(); // Read the header row
                int i = 0;
                while((line = data.readLine()) != null) 
                {
                    
                    Customer customer = new Customer(line.split("\t")[0], line.split("\t")[1], line.split("\t")[2], line.split("\t")[3]);
                    this.customers.add(customer);
                    i++;
                    

                }
                data.close();
            }
            
            
            
            
            //while

            
        }  
        catch(IOException e)  
        {  
            
            e.printStackTrace();  
        }
    }
    
    private void showAllCustomers()
    {
        for(int i = 0; i < this.customers.size(); i++)
        {
            this.customerTable.insertRow(this.customerTable.getRowCount(), new Object[] {this.customers.get(i).id, this.customers.get(i).name, this.customers.get(i).email, this.customers.get(i).phone});
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        labelEmail1 = new javax.swing.JLabel();
        editCustomer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 150));
        jPanel1.setMaximumSize(new java.awt.Dimension(340, 460));
        jPanel1.setMinimumSize(new java.awt.Dimension(340, 460));
        jPanel1.setPreferredSize(new java.awt.Dimension(340, 460));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Customer Management");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 380, -1));

        addButton.setBackground(new java.awt.Color(153, 153, 255));
        addButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add New Customer");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 500, 210, 45));

        jTable1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Phone", "Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 1080, 410));

        backButton.setBackground(new java.awt.Color(153, 153, 255));
        backButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 140, 45));

        searchField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });
        jPanel1.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 200, 30));

        labelEmail1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelEmail1.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail1.setText("Search:");
        jPanel1.add(labelEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 110, 30));

        editCustomer.setBackground(new java.awt.Color(153, 153, 255));
        editCustomer.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        editCustomer.setForeground(new java.awt.Color(255, 255, 255));
        editCustomer.setText("Edit Customer");
        editCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(editCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 210, 45));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 1140, 570));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/images/pexels-engin-akyurt-1435904.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        this.setVisible(false);
        AddNewCustomer ancf = new AddNewCustomer();
        ancf.setLocation(this.getLocation());
        ancf.setVisible(true);
        ancf.setResizable(false);
    }//GEN-LAST:event_addButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        AdminDashboard ad = new AdminDashboard();
        ad.setLocation(this.getLocation());
        ad.setVisible(true);
        ad.setResizable(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldKeyPressed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        String query = searchField.getText();
        this.customerTable = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(this.customerTable);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)" + query.trim()));
    }//GEN-LAST:event_searchFieldKeyReleased

    private void editCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCustomerActionPerformed
        
        try
        {
            String id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            Customer customer = new Customer(id);
            EditCustomer ecf = new EditCustomer(customer);
            this.setVisible(false);
            ecf.setLocation(this.getLocation());
            ecf.setVisible(true);
            ecf.setResizable(false);
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Select a customer please", "Selection Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_editCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton editCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelEmail1;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
