/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FAWZAN
 */
public class EditCar extends javax.swing.JFrame {
    private Car car;
    DefaultTableModel table;
    /**
     * Creates new form AdminDashboard
     * @param email
     */
    public EditCar(Car car) {
        initComponents();
        this.car = car;
        
        
        this.manufacturerField.setText(car.manufacturer);
        this.modelField.setText(car.model);
        this.colorField.setText(car.color);
        this.seatsField.setText(car.seats);
        this.rentField.setText(car.rent);
        if(car.status.compareTo("Available") == 0)
            this.statusField.setSelectedIndex(0);
        else
            this.statusField.setSelectedIndex(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        manufacturerLabel = new javax.swing.JLabel();
        manufacturerField = new javax.swing.JTextField();
        modelLabel = new javax.swing.JLabel();
        modelField = new javax.swing.JTextField();
        colorLabel = new javax.swing.JLabel();
        colorField = new javax.swing.JTextField();
        seatsLabel = new javax.swing.JLabel();
        seatsField = new javax.swing.JTextField();
        rentLabel = new javax.swing.JLabel();
        rentField = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();
        statusField = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 150));
        jPanel1.setMaximumSize(new java.awt.Dimension(340, 460));
        jPanel1.setMinimumSize(new java.awt.Dimension(340, 460));
        jPanel1.setPreferredSize(new java.awt.Dimension(340, 460));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Edit Car Details");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 380, -1));

        saveButton.setBackground(new java.awt.Color(153, 153, 255));
        saveButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 160, 45));

        backButton.setBackground(new java.awt.Color(153, 153, 255));
        backButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 140, 45));

        manufacturerLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        manufacturerLabel.setForeground(new java.awt.Color(255, 255, 255));
        manufacturerLabel.setText("Manufacturer:");
        jPanel1.add(manufacturerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, 30));

        manufacturerField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        manufacturerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturerFieldActionPerformed(evt);
            }
        });
        manufacturerField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                manufacturerFieldKeyPressed(evt);
            }
        });
        jPanel1.add(manufacturerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 200, 30));

        modelLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        modelLabel.setForeground(new java.awt.Color(255, 255, 255));
        modelLabel.setText("Model:");
        jPanel1.add(modelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, 30));

        modelField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        modelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelFieldActionPerformed(evt);
            }
        });
        modelField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                modelFieldKeyPressed(evt);
            }
        });
        jPanel1.add(modelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 200, 30));

        colorLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        colorLabel.setForeground(new java.awt.Color(255, 255, 255));
        colorLabel.setText("Color:");
        jPanel1.add(colorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 110, 30));

        colorField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        colorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorFieldActionPerformed(evt);
            }
        });
        colorField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                colorFieldKeyPressed(evt);
            }
        });
        jPanel1.add(colorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 200, 30));

        seatsLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        seatsLabel.setForeground(new java.awt.Color(255, 255, 255));
        seatsLabel.setText("No. of Seats");
        jPanel1.add(seatsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, 30));

        seatsField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        seatsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsFieldActionPerformed(evt);
            }
        });
        seatsField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                seatsFieldKeyPressed(evt);
            }
        });
        jPanel1.add(seatsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 200, 30));

        rentLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rentLabel.setForeground(new java.awt.Color(255, 255, 255));
        rentLabel.setText("Rent/Day in RM:");
        jPanel1.add(rentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 160, 30));

        rentField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        rentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentFieldActionPerformed(evt);
            }
        });
        rentField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rentFieldKeyPressed(evt);
            }
        });
        jPanel1.add(rentField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 200, 30));

        statusLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(255, 255, 255));
        statusLabel.setText("Status: ");
        jPanel1.add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 80, 30));

        statusField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        statusField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Not Available" }));
        jPanel1.add(statusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 430, 470));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/images/pexels-engin-akyurt-1435904.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        this.car.manufacturer = manufacturerField.getText();
        this.car.model = modelField.getText();
        this.car.color = colorField.getText();
        this.car.seats = seatsField.getText();
        this.car.rent = rentField.getText();
        this.car.status = statusField.getSelectedItem().toString();
        
        if(car.validate())
        {
            car.update();
            this.setVisible(false);
            CarManagement cmf = new CarManagement();
            cmf.setLocation(this.getLocation());
            cmf.setVisible(true);
            cmf.setResizable(false);
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        CarManagement cmf = new CarManagement();
        cmf.setLocation(this.getLocation());
        cmf.setVisible(true);
        cmf.setResizable(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void manufacturerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacturerFieldActionPerformed

    private void manufacturerFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manufacturerFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacturerFieldKeyPressed

    private void modelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelFieldActionPerformed

    private void modelFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modelFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelFieldKeyPressed

    private void colorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorFieldActionPerformed

    private void colorFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_colorFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorFieldKeyPressed

    private void seatsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatsFieldActionPerformed

    private void seatsFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seatsFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatsFieldKeyPressed

    private void rentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentFieldActionPerformed

    private void rentFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rentFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField colorField;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField manufacturerField;
    private javax.swing.JLabel manufacturerLabel;
    private javax.swing.JTextField modelField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField rentField;
    private javax.swing.JLabel rentLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField seatsField;
    private javax.swing.JLabel seatsLabel;
    private javax.swing.JComboBox<String> statusField;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
