/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import javax.swing.JOptionPane;

/**
 *
 * @author FAWZAN
 */
public class EditCustomer extends javax.swing.JFrame {
    private Customer customer;
    /**
     * Creates new form Welcome
     * @param customer
     */
    public EditCustomer(Customer customer) {
        
        initComponents();
        
        this.customer = customer;
        
        emailField.setText(customer.email);
        nameField.setText(customer.name);
        phoneField.setText(customer.phone);
        this.securityQuesField.setText(customer.securityQ);
        this.securityAnsField.setText(customer.securityAns);
        this.passwordField2.setText(customer.password);
        this.passwordField3.setText(customer.password);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        labelWelcome1 = new javax.swing.JLabel();
        registerButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        securityQuesField = new javax.swing.JTextField();
        securityAnsField = new javax.swing.JTextField();
        passwordField2 = new javax.swing.JPasswordField();
        passwordField3 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 150));
        jPanel1.setMaximumSize(new java.awt.Dimension(340, 460));
        jPanel1.setMinimumSize(new java.awt.Dimension(340, 460));
        jPanel1.setPreferredSize(new java.awt.Dimension(340, 460));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 110, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 110, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Phone");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 110, 30));

        emailField.setEditable(false);
        emailField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        emailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailFieldKeyPressed(evt);
            }
        });
        jPanel1.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 200, 30));

        nameField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameFieldKeyPressed(evt);
            }
        });
        jPanel1.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 200, 30));

        phoneField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });
        phoneField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneFieldKeyPressed(evt);
            }
        });
        jPanel1.add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 200, 30));

        registerButton.setBackground(new java.awt.Color(153, 153, 255));
        registerButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Cancel");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 140, 45));

        labelWelcome1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelWelcome1.setForeground(new java.awt.Color(255, 255, 255));
        labelWelcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWelcome1.setText("Edit Customer Details");
        jPanel1.add(labelWelcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 380, -1));

        registerButton1.setBackground(new java.awt.Color(153, 153, 255));
        registerButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        registerButton1.setForeground(new java.awt.Color(255, 255, 255));
        registerButton1.setText("Save");
        registerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 140, 45));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Security Question");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 190, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Security Answer");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 180, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Password");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 180, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Confirm Password");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 170, 30));

        securityQuesField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        securityQuesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityQuesFieldActionPerformed(evt);
            }
        });
        securityQuesField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                securityQuesFieldKeyPressed(evt);
            }
        });
        jPanel1.add(securityQuesField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 200, 30));

        securityAnsField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        securityAnsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityAnsFieldActionPerformed(evt);
            }
        });
        securityAnsField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                securityAnsFieldKeyPressed(evt);
            }
        });
        jPanel1.add(securityAnsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 200, 30));

        passwordField2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        passwordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordField2KeyPressed(evt);
            }
        });
        jPanel1.add(passwordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 200, 30));

        passwordField3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        passwordField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordField3KeyPressed(evt);
            }
        });
        jPanel1.add(passwordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 200, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 540, 540));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/images/pexels-engin-akyurt-1435904.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        
        this.setVisible(false);
        CustomerManagement cmf = new CustomerManagement();
        cmf.setLocation(this.getLocation());
        cmf.setVisible(true);
        cmf.setResizable(false);
            
    }//GEN-LAST:event_registerButtonActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void emailFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldKeyPressed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void nameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldKeyPressed

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldActionPerformed

    private void phoneFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldKeyPressed

    private void registerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButton1ActionPerformed
        this.customer.name = nameField.getText();
        this.customer.phone = phoneField.getText();
        this.customer.securityQ = this.securityQuesField.getText();
        this.customer.securityAns = this.securityAnsField.getText();
        this.customer.password = String.valueOf(this.passwordField2.getPassword());
        this.customer.confirmPass = String.valueOf(this.passwordField3.getPassword());
        
        if(this.customer.updateValidate())
        {
            if(this.customer.update())
            {
                this.setVisible(false);
                CustomerManagement cmf = new CustomerManagement();
                cmf.setLocation(this.getLocation());
                cmf.setVisible(true);
                cmf.setResizable(false);
            }
        }
    }//GEN-LAST:event_registerButton1ActionPerformed

    private void securityQuesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityQuesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityQuesFieldActionPerformed

    private void securityQuesFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_securityQuesFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityQuesFieldKeyPressed

    private void securityAnsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityAnsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityAnsFieldActionPerformed

    private void securityAnsFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_securityAnsFieldKeyPressed

    }//GEN-LAST:event_securityAnsFieldKeyPressed

    private void passwordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordField2KeyPressed

    }//GEN-LAST:event_passwordField2KeyPressed

    private void passwordField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordField3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordField3KeyPressed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelWelcome1;
    private javax.swing.JTextField nameField;
    private javax.swing.JPasswordField passwordField2;
    private javax.swing.JPasswordField passwordField3;
    private javax.swing.JTextField phoneField;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton registerButton1;
    private javax.swing.JTextField securityAnsField;
    private javax.swing.JTextField securityQuesField;
    // End of variables declaration//GEN-END:variables
}
