/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import javax.swing.JOptionPane;

/**
 *
 * @author FAWZAN
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emailField2 = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        securityQuesField = new javax.swing.JTextField();
        securityAnsField = new javax.swing.JTextField();
        passwordField2 = new javax.swing.JPasswordField();
        passwordField3 = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        labelWelcome1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelForgotPass = new javax.swing.JLabel();
        labelPassword1 = new javax.swing.JLabel();
        passwordField1 = new javax.swing.JPasswordField();
        labelEmail1 = new javax.swing.JLabel();
        emailField1 = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        resetPassButton = new javax.swing.JButton();
        labelWelcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 150));
        jPanel1.setMaximumSize(new java.awt.Dimension(340, 460));
        jPanel1.setMinimumSize(new java.awt.Dimension(340, 460));
        jPanel1.setPreferredSize(new java.awt.Dimension(340, 460));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Phone:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 110, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Security Question:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 190, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Security Answer:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 180, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Password:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 180, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Confirm Pass:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 170, 30));

        emailField2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        emailField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailField2ActionPerformed(evt);
            }
        });
        emailField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailField2KeyPressed(evt);
            }
        });
        jPanel1.add(emailField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 200, 30));

        nameField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameFieldKeyPressed(evt);
            }
        });
        jPanel1.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 200, 30));

        phoneField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });
        phoneField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneFieldKeyPressed(evt);
            }
        });
        jPanel1.add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 200, 30));

        securityQuesField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        securityQuesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityQuesFieldActionPerformed(evt);
            }
        });
        securityQuesField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                securityQuesFieldKeyPressed(evt);
            }
        });
        jPanel1.add(securityQuesField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 200, 30));

        securityAnsField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        securityAnsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityAnsFieldActionPerformed(evt);
            }
        });
        securityAnsField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                securityAnsFieldKeyPressed(evt);
            }
        });
        jPanel1.add(securityAnsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 200, 30));

        passwordField2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        passwordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordField2KeyPressed(evt);
            }
        });
        jPanel1.add(passwordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 200, 30));

        passwordField3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        passwordField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordField3KeyPressed(evt);
            }
        });
        jPanel1.add(passwordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 200, 30));

        registerButton.setBackground(new java.awt.Color(153, 153, 255));
        registerButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 140, 45));

        labelWelcome1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelWelcome1.setForeground(new java.awt.Color(255, 255, 255));
        labelWelcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWelcome1.setText("Welcome New User");
        jPanel1.add(labelWelcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 380, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 460, 540));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 150));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelForgotPass.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelForgotPass.setForeground(new java.awt.Color(255, 255, 255));
        labelForgotPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelForgotPass.setText("Forgot Password?");
        jPanel2.add(labelForgotPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 160, 30));

        labelPassword1.setBackground(new java.awt.Color(255, 255, 255));
        labelPassword1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelPassword1.setForeground(new java.awt.Color(255, 255, 255));
        labelPassword1.setText("Password:");
        jPanel2.add(labelPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 172, 100, 35));

        passwordField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        passwordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordField1KeyPressed(evt);
            }
        });
        jPanel2.add(passwordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 177, 200, 30));

        labelEmail1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelEmail1.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail1.setText("Email:");
        jPanel2.add(labelEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 103, 110, 30));

        emailField1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        emailField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailField1ActionPerformed(evt);
            }
        });
        emailField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailField1KeyPressed(evt);
            }
        });
        jPanel2.add(emailField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 106, 200, 30));

        loginButton.setBackground(new java.awt.Color(153, 153, 255));
        loginButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 140, 45));

        resetPassButton.setBackground(new java.awt.Color(153, 153, 255));
        resetPassButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        resetPassButton.setForeground(new java.awt.Color(255, 255, 255));
        resetPassButton.setText("Reset Password");
        resetPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPassButtonActionPerformed(evt);
            }
        });
        jPanel2.add(resetPassButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 180, 45));

        labelWelcome.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelWelcome.setForeground(new java.awt.Color(255, 255, 255));
        labelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWelcome.setText("Welcome Back User");
        jPanel2.add(labelWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 380, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 420, 540));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/images/pexels-engin-akyurt-1435904.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordField2KeyPressed
        
    }//GEN-LAST:event_passwordField2KeyPressed

    private void securityAnsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityAnsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityAnsFieldActionPerformed

    private void securityAnsFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_securityAnsFieldKeyPressed
        
    }//GEN-LAST:event_securityAnsFieldKeyPressed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String email = emailField1.getText().toLowerCase();
        String password = String.valueOf(passwordField1.getPassword());
        
        User user = new User(email, password);
        
        if(user.validate())
        {
            if(user.login())
            {

                if(user.isAdmin())
                {
                    this.setVisible(false);
                    AdminDashboard ad = new AdminDashboard();
                    ad.setLocation(this.getLocation());
                    ad.setVisible(true);
                    ad.setResizable(false);
                }
                else
                {
                    this.setVisible(false);
                    
                    CustomerDashboard cd = new CustomerDashboard(user.email);
                    cd.setLocation(this.getLocation());
                    cd.setVisible(true);
                    cd.setResizable(false);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Login Failed", "Login Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String email = emailField2.getText().toLowerCase();
        String name = nameField.getText();
        String phone = phoneField.getText();
        String securityQ = securityQuesField.getText();
        String securityAns = securityAnsField.getText();
        String password = String.valueOf(passwordField2.getPassword());
        String confirmPass = String.valueOf(passwordField3.getPassword());
        
        
        Customer customer = new Customer(name, email, phone, password, confirmPass, securityQ, securityAns);
        
        if(customer.validate())
        {
            
            this.setVisible(false);
            CustomerDashboard cd = new CustomerDashboard(customer.register());
            cd.setLocation(this.getLocation());
            cd.setVisible(true);
            cd.setResizable(false);
            
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void resetPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPassButtonActionPerformed
        ResetPasswordRequest rprf = new ResetPasswordRequest();
        this.setVisible(false);
        
        rprf.setLocation(this.getLocation());
        rprf.setVisible(true);
        rprf.setResizable(false);
    }//GEN-LAST:event_resetPassButtonActionPerformed

    private void emailField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailField1ActionPerformed

    private void emailField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailField1KeyPressed

    private void passwordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordField1KeyPressed

    private void passwordField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordField3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordField3KeyPressed

    private void emailField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailField2ActionPerformed

    private void emailField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailField2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailField2KeyPressed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void nameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldKeyPressed

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldActionPerformed

    private void phoneFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldKeyPressed

    private void securityQuesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityQuesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityQuesFieldActionPerformed

    private void securityQuesFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_securityQuesFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityQuesFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailField1;
    private javax.swing.JTextField emailField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelEmail1;
    private javax.swing.JLabel labelForgotPass;
    private javax.swing.JLabel labelPassword1;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JLabel labelWelcome1;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JPasswordField passwordField1;
    private javax.swing.JPasswordField passwordField2;
    private javax.swing.JPasswordField passwordField3;
    private javax.swing.JTextField phoneField;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton resetPassButton;
    private javax.swing.JTextField securityAnsField;
    private javax.swing.JTextField securityQuesField;
    // End of variables declaration//GEN-END:variables
}
